SOURCE = 0
QUEUE_SIZE = 2
WINDOW_NAME = "Real-Time Privacy Pipeline"

DETECT_INTERVAL = 6
CONFIDENCE = 0.55
IMAGE_SIZE = 320
PRIVACY_FAIL_SAFE = True
AUDIT_LOG_PATH = "privacy_audit.jsonl"
SAVE_ORIGINAL_FRAMES = False
LONG_TEST_SECONDS = 3600
